### ISSUE TITLE
Feature: User Can Submit a Trail

### ISSUE THREAD

**Issue by lyn-kim** [lyn-kim/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can upload new trails to the app by providing FIVE pertinent information regarding the trail:
1. Name
2. Length
3. Address
4. Difficulty
5. Image

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile view:
![Feature 1 - Submit Mobile](https://user-images.githubusercontent.com/89041368/153962241-21553274-0c19-4ae9-a90b-afa11a0a9508.JPG)

Desktop view:
![Feature 1 - Submit Desktop](https://user-images.githubusercontent.com/89041368/153962270-91944af9-c4ba-4a26-b68e-fd2ec085ff33.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to the exported create.sql from db designer
- [x] Update `data.sql` to:
   - [x] Insert admin to userId:1

### ☁️ Server

- [x] Add all required packages (pg, express, path, client-error, error-middleware, uploads-middleware, dotenv-config)
- [x] Define variables for pg.Pool(), express() and express.json()
- [x] Call app.use(jsonMiddleware)
- [x] Update `server/index.js` to respond to POST requests for user sign-in (admin verification)
   - [x] Ensure that all required info are provided in the body of the POST request (username and password)
   - [x] Define sql and params const variables
   - [x] Query the db to look for user
   - [x] Verify user info (pass, hashedpass, check token)
- [x] Update `server/index.js` to respond to POST requests for trail submission 
   - [x] Ensure that all required info (trail name, length, difficulty, address and image) are provided in the body of the POST request - if not, send ClientError
   - [x] Define url, sql, and params const variables
   - [x] Query the db and insert new trail into db
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create navbar component
- [x] Create trail submission component containing a form element with 5 required fields: name (text), length (number with 1 decimal place), address (text), difficulty (select) and image to choose from file
   - [x] Image preview updates when file is attached to replace placeholder img 
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Make sure submitted trails are recorded in the database with userId: 1
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
